#!/usr/bin/env gtkwave -S
# GTKWave TCL Script
# Generated by GTKWave MCP Server

# Load waveform file
gtkwave::loadFile "/Users/qlss/Documents/mcp4eda/test_gtkwave.vcd"

gtkwave::addSignalsFromList "top.clk"
gtkwave::addSignalsFromList "top.data"
gtkwave::setMarker 100ns
gtkwave::setFromTime 0
gtkwave::setToTime 200ns
